# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  - main  # Manual or scheduled only

schedules:
  # TEST & UAT every weekday at 7:30 AM Quebec (UTC+5 = 12:30)
  - cron: "30 12 * * 1-5"
    displayName: Run TEST & UAT at 7:30 AM Quebec Time
    branches:
      include:
        - main
    always: 'true'

  # DEV at 9:30 AM Quebec (UTC+5 = 14:30)
  - cron: "30 14 * * 1-5"
    displayName: Run DEV before day starts
    branches:
      include:
        - main
    always: 'true'

  # DEV at 6:30 PM Quebec (UTC+5 = 23:30)
  - cron: "30 23 * * 1-5"
    displayName: Run DEV before day ends
    branches:
      include:
        - main
    always: 'true'

pool:
  name: 'Votre Sante Agent Pool'

steps:
  - task: NodeTool@0
    inputs:
      versionSpec: '18'
    displayName: 'Install Node.js'

  - script: npm ci
    displayName: 'Install dependencies'

  - script: npx playwright install --with-deps
    displayName: 'Install Playwright and browsers'

  - script: |
      echo "Checking scheduled environment..."
      CURRENT_HOUR=$(date -u +"%H")

      if [ "$CURRENT_HOUR" -eq 12 ]; then
        echo "Running TEST & UAT"
        npx playwright test tests --project=test-chromium --project=UAT-chromium
      elif [ "$CURRENT_HOUR" -eq 14 ] || [ "$CURRENT_HOUR" -eq 23 ]; then
        echo "Running DEV"
        npx playwright test tests --project=dev-chromium
      else
        npx playwright test tests --project=test-chromium
      fi
    displayName: 'Run Playwright Tests for Scheduled Environment'
    env:
      CI: 'true'

  - task: PublishPipelineArtifact@1
    inputs:
      targetPath: playwright-report.html
      artifact: playwright-report
      publishLocation: pipeline
    condition: succeededOrFailed()
    displayName: 'Publish Playwright Custom HTML Report'
